export const theme = {
  colors: {
    background: '#ffffff',
    surface: '#ffffff',
    surfaceAlt: '#f7f7f5',
    text: '#37352f',
    textMuted: '#787774',
    textSubtle: '#9b9a97',
    textInverse: '#ffffff',
    border: '#ebebea',
    borderSubtle: '#f1f1ef',
    accent: '#2383e2',
    done: '#0f7b6c',
    doneSoft: '#e0efe4',
    pending: '#d9730d',
    pendingSoft: '#fbecdd',
    today: '#ea580c',
    todaySoft: '#fff1e6',
  },
  spacing: {
    xs: 4,
    sm: 8,
    md: 12,
    lg: 16,
    xl: 24,
  },
  radius: {
    sm: 4,
    md: 8,
    lg: 14,
    pill: 999,
  },
  font: {
    xs: 10,
    sm: 12,
    md: 14,
    lg: 16,
    xl: 22,
  },
} as const;
